
install.packages("knitr")
install.packages("printr")
install.packages("formatR")
install.packages("readxl")
install.packages("ggplot2")
install.packages("pastecs")
install.packages("psych")
install.packages("Hmisc")
install.packages("lattice")
install.packages("lmtest")
install.packages("BSDA")
